name: biofago_erwinia
owner: josediogomoura
description: Genomic analysis tool for Erwinia amylovora
long_description: |
  BioFago Erwinia is a comprehensive genomic analysis tool for Erwinia amylovora strains.
  It performs locus typing, plasmid detection, streptomycin resistance gene identification, and CRISPR genotype analysis.
categories:
  - Sequence Analysis
homepage_url: https://github.com/beach-fossils/BioFago
remote_repository_url: https://github.com/beach-fossils/BioFago
type: unrestricted