name: BioFago CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install BLAST
      run: |
        chmod +x external/blast/install_blast.sh
        sudo ./external/blast/install_blast.sh

    - name: Run unit tests
      run: python -m unittest discover tests/unit

    - name: Run integration tests
      run: python -m unittest discover tests/integration

    # Add error handling
    - name: Check for errors
      if: failure()
      run: |
        echo "The workflow failed. Please check the logs for more information."
        exit 1
    
    
